server:
  port: 8888
  servlet:
    #    context-path: /
    jsp:
      init-parameters:
        development: true
    session:
      tracking-modes: cookie


spring:
  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**


  #database
  datasource:
    url: "jdbc:mariadb://localhost:3306/mini_proj2"
    username: "root"
    password: "Qortmdcks95"
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${naver_id} # Replace with actual client ID
            client-secret: ${naver_secret}  # Replace with actual client secret
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: ${google_id}  # Fill in your Google client ID
            client-secret:  ${google_secret} # Fill in your Google client secret
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

    jwt:
      secret: ${jwt_secret}

  profiles:
    include: API-KEY



mybatis:
  config-location: classpath:mybatis-config.xml  # MyBatis ?? ?? ??
  mapper-locations: classpath:mapper/**/*.xml  # Mapper ?? ??


gpt:
  model: gpt-3.5-turbo
  api:
    key: ${gpt_api_key}
    url: https://api.openai.com/v1/chat/completions


