server:
  port: 8888
  servlet:
#    context-path: /
    jsp:
      init-parameters:
        development: true


spring:
  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**


  #database
  datasource:
    url: "jdbc:mariadb://localhost:3306/mini_proj2"
    username: "root"
    password: "Qortmdcks95"
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    user:
      name: test@test.com
      password: 1234



mybatis:
  config-location: classpath:mybatis-config.xml  # MyBatis ?? ?? ??
  mapper-locations: classpath:mapper/**/*.xml  # Mapper ?? ??



appkey: PSz4sAmyn2ya3D0cnr5SEqrcr9782EGz3J2X
appsecret: t/GjDtBann2Ap5cpaFu/M2jqcXX81pyrTLCsmi+xSKxcc7U4qFJImW+lcsCLwKvBRJ6or7OVFEzzu3GCB1yq9ydy6EgZZHYfTSKk4zVof4Qx5RhPcnEdf5qfKBUazJ/cA4E5nr76wZk0xDmtgVmYia5pMrCPhteE39XxhPWUALwgg5ZyMDY=
access_token : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImVmZmVjNDY3LWQzOGYtNDZmZi1iNWQwLWFlNDk4NzMyZTZhMCIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTcxNTA4MTM1NSwiaWF0IjoxNzE0OTk0OTU1LCJqdGkiOiJQU3o0c0FteW4yeWEzRDBjbnI1U0VxcmNyOTc4MkVHejNKMlgifQ.lbBysTsYLPWeeeV7NlzWJeF5TmiB6zQQkYrsLtwbKxl_hAF7ESkGriP6WFBey4aCCwwKhvYkAm4veOghSkmGtA

gpt:
  model: gpt-3.5-turbo
  api:
    key: sk-proj-K1Uy9YnlECGlQpfbsNG8T3BlbkFJb509P4rSyaLjtGcJJPJ0
    url: https://api.openai.com/v1/chat/completions


#  677982bdcd6549329d32edfcb90766bd

#https://newsapi:
#  org/v2/top-headlines?country=kr&apiKey=677982bdcd6549329d32edfcb90766bd: